name: Eleventy Build and Deploy
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
        with:
          args: --output dist
          install_dependencies: true
